.\"                                      Hey, EMACS: -*- nroff -*-
.TH KVQC2D 1 "December 2, 2011"
.SH NAME
kvqc2d \- non-realtime automatic quality controls for weather observation data
.SH SYNOPSIS
.B kvqc2d
.RI [ options ]
.SH DESCRIPTION
This manual page does not document
.B kvqc2d
command. For documentation, please see http://kvalobs.wiki.met.no/
.PP
.SH OPTIONS
See the source code kvapp.cc and Qc2App.cc to find out the available
options. These files are available from svn.met.no
.SH SEE ALSO
.BR http://kvalobs.wiki.met.no/
and
.BR svn.met.no
.SH AUTHOR
kvqc2d was written at Met.no, the norwegian meteorological
institute. Questions may be directed to <kvalobs-dev@met.no>.
.PP
This manual page was written by Alexander B\(:urger
<alexander.buerger@met.no> in October 2011.
