Document: kvqc2
Title: Debian kvqc2 Manual
Author: <insert document author here>
Abstract: This manual describes what kvqc2 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kvqc2/kvqc2.sgml.gz

Format: postscript
Files: /usr/share/doc/kvqc2/kvqc2.ps.gz

Format: text
Files: /usr/share/doc/kvqc2/kvqc2.text.gz

Format: HTML
Index: /usr/share/doc/kvqc2/html/index.html
Files: /usr/share/doc/kvqc2/html/*.html

  
